server:
  port: 3001

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

product:
  service:
    url: http://localhost:4001/productdata
